### ISSUE TITLE
Lookup table

### ISSUE THREAD

**Issue by marijnvdwerf** [nviennot/reversing-mono4k#1]
The lookup table in the SPI flash seems to be a conversion table between Unicode and GB18030. The fonts seem to be organized based on the latter: https://encoding.spec.whatwg.org/gb18030.html

![image](https://user-images.githubusercontent.com/737603/149119776-ed003cfc-94fe-43f1-ba9c-571283722705.png)

**Comment by nviennot** [comment]
Awesome! well done!

I've added your discovery to the writeup
