### ISSUE TITLE
External flash data

### ISSUE THREAD

**Issue by marijnvdwerf** [nviennot/reversing-mono4k#2]
Aside from the data at the end, the external flash seems to contain some (outdated?) data. 

The first font starts with some glyphs that are also later in the font, leading me to believe that it used to start at a lower address. The actual fonts that get loaded seem to be at `5E 0000` for the 16px font  and `6A 0000` for the 12px font and (the firmware also appears to have support for a 24px font at `B8 7000`?)

I suspect the firmware is based on that of the Photon Mono SE. The firmware of those is available on the Anycubic website, and it does appear to feature a 480px-wide screen, as well as 3 differently sized fonts. Although I haven't validated the latter, the data at the end of `PMS_UI_001_bin` does appear to be the same stuff thrice, bigger each time.

**Comment by nviennot** [comment]
You're right! I The junk images line up perfectly with the Mono SE firmware images, specifically the junk corresponds to ui-24 and ui-25 of the mono SE.

The only difference I can see is the image 29.:

Mono 4K:
![image](https://user-images.githubusercontent.com/297060/149457881-eb9f2a63-8dd7-466a-b3c9-b45c5a87ccf6.png)

Mono SE:
![image](https://user-images.githubusercontent.com/297060/149457884-ff43cfec-61f2-4088-9fce-12fad6000d51.png)

That means that the 3rd font present in the Mono 4K is not garbage.

Nice!
